<p><strong>CLAUSULA QUINTA VALOR Y FORMA DE PAGO</strong></p>
<p>Por este contrato el ADHERENTE, adquiere el beneficio de ser MIEMBRO VIP DE ONE CLASS GROUP. El valor total de los servicios turísticos adquiridos y descuentos en este contrato de adhesión es de $%%VALORCONTRATO%% (%%VALORCONTRATOLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA).</p>
<p><strong>5.1 VALOR PAGADO</strong><br/>
  a) La cuota inicial pactada es de $%%VALORCUOTAINICIAL%% (%%VALORCUOTAINICIALLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA).<br />
  b) La cuota inicial pagada a la fecha es de $%%PAGOCUOTAINICIAL%% (%%PAGOCUOTAINICIALLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA). <br />  
  c) El saldo de la cuota inicial pactada equivalente a $%%VALORSALDOCUOTAINICIAL%% (%%VALORSALDOCUOTAINICIALLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA). Será pagada por el ADHERENTE a partir del %%FECHAINICIALPRIMERACUOTA%% en %%NUMEROCUOTASCUOTAINICIAL%% cuotas de $%%VALORCUOTACUOTAINICIAL%% (%%VALORCUOTACUOTAINICIALLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA).</p>
<p><strong>5.2 VALOR FINANCIADO</strong><br />
  a) El saldo a financiar equivalente a $%%VALORFINACIADO%% (%%VALORFINANCIADOLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA). Sera pagadero por el ADHERENTE a partir del %%FECHAPRIMERACUOTA%% en %%NUMEROCUOTAS%% cuota(s) de $%%VALORCUOTA%% (%%VALORCUOTALETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMERICA).</p>
