<div style="text-align: justify;">
  <p align="center"><strong>PAGARÉ No %%NUMEROPAGARE%%</strong></p>
  <p align="center"><strong>POR UN VALOR DE (%%SALDOAFINANCIARLETRAS%%) (USD$ %%SALDOAFINANCIAR%%) ESTE VALOR ES EL SALDO A FINACIAR</strong></p>
  <p align="center"></p>
  <p>Yo, %%NOMBRECOMPLETOTITULAR%% identificado(a) con <strong>%%IDENTIFICACIONTITULAR%%</strong>, con domicilio y residencia en la ciudad de Guayaquil, respectivamente, me comprometo a pagar incondicionalmente a NASELLORIL S.A, o a su orden, en sus oficinas en el Centro Comercial Albán Borja puerta 1 local 58 A, la suma de ( %%SALDOAFINANCIARLETRAS%% DOLARES DE LOS ESTADOS UNIDOS DE NORTE AMÉRICA 0/100) (<strong>USD$ %%SALDOAFINANCIAR%%</strong>) pagaderos en %%NUMEROCUOTAS%% cuotas mensuales y consecutivas; por un valor de (<strong>USD$ %%VALORCUOTASALDO%%</strong>). El pago de dicha cuota se realizará en dólares de los estados unidos de norte américa a partir del %%FECHAPRIMERPAGOSALDO%%. En caso de mora y mientras ella subsista pagaré intereses moratorios a la tasa máxima autorizada por la Superintendencia Financiera para el periodo correspondiente. De igual manera me obligo a pagar todos los gastos y costos de la cobranza judicial y honorarios de abogados.</p>
  <p>En el evento que el deudor no pague en el plazo estipulado una o más cuotas, el tenedor de este título podrá declarar insubsistente los plazos de esta obligación y pedir su inmediato pago total o el pago del saldo.</p>
  <p>También aceptamos que NASELLORIL S.A., declare de plazo vencido la obligación a que se refiere este pagaré y exigir su pago total en el evento en que sea perseguido judicialmente.</p>
  <p>El recibo de abono de parciales no implica novación y cualquier pago que se efectúe se imputará primero a gastos, penalidades, y por ultimo a capital. El suscriptor de este pagare hace constar que la obligación de pagarla indivisiblemente y solidariamente subsiste en caso de prorroga o prorrogas o de cualquier modificación a lo estipulado, aunque se pacte con uno solo se los suscriptores. El deudor declara que la suma que debe conforme a este pagaré no estará sujeta ni a deducciones ni a descuentos de cualquier naturaleza, incluyendo sin limitación cualquier impuesto que pueda gravar su pago, por lo tanto, en caso de existir alguna de estas deducciones o descuentos, el deudor deberá aumentar la suma a pagar de tal manera que el tenedor reciba siempre el valor estipulado del pagaré. Declaro excusada la presente y noticia de rechazo. El deudor acepta desde ahora el endoso, cesión o transferencia que de este pagare hiciere NASELLORIL S.A. a cualquier título, todos los gastos e impuestos relacionados con la suscripción de este pagaré serán por cuenta del deudor.</p>
  <p>En constancia de lo anterior, se firma el presente pagaré el %%FECHAHOY%%, en la ciudad de GUAYAQUIL.</p>
  <p>El Deudor,</p>
</div>